sudo: required

services:
  - docker

before_install:
  - gem update --system 3.2.3  # RubyGemsを最新バージョンにアップデート
  - gem install bundler -v 2.3.0 # Bundler 2.xをインストール
  - bundle config set --local deployment 'true'  # `--deployment` フラグの代替
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' web rails test
